version: '2'
services:
  eurekaserver:
     image:   smia/tmx-eureka-service:chapter8
     ports:
         - "8761:8761"
  configserver:
      image: smia/tmx-config-service:chapter8
      ports:
         - "8888:8888"
      environment:
         EUREKASERVER_PORT: 8761
         EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
         ENCRYPT_KEY:       "IMSYMMETRIC"
  zuulserver:
      image: smia/tmx-zuul-service:chapter8
      ports:
        - "5555:5555"
      environment:
        PROFILE: "default"
        SERVER_PORT: "5555"
        CONFIGSERVER_PORT: 8888
        EUREKASERVER_PORT: 8761
        CONFIGSERVER_URI: "http://configserver:8888"
        EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=p0stgr@s
      - POSTGRES_DB=eagle_eye_local
  licensingservice:
    image: smia/tmx-licensing-service:chapter8
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      REDIS_PORT:          "6379"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  organizationservice:
    image: smia/tmx-organization-service:chapter8
    ports:
      - "8085:8085"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8085"
      CONFIGSERVER_URI: "http://configserver:8888"
      EUREKASERVER_URI: "http://eurekaserver:8761/eureka/"
      KAFKASERVER_URI: "kafkaserver"
      ZKSERVER_URI: "kafkaserver"
      DATABASESERVER_PORT: "5432"
      EUREKASERVER_PORT:   "8761"
      CONFIGSERVER_PORT:   "8888"
      ZUULSERVER_PORT:     "5555"
      KAFKASERVER_PORT:    "2181"
      ENCRYPT_KEY:       "IMSYMMETRIC"
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
  kafkaserver:
    image: spotify/kafka
    ports:
      - 2181:2181
      - 9092:9092
